language: python

os: linux

dist: xenial

python:
 - "3.5"
 - "3.6"
 - "3.8"
 - "pypy3"

jobs:
  include:
    - os: linux
      python: "3.7"
      after_success:
        - travis_retry pip install coveralls
        - coveralls

    - os: osx
      language: generic

install:
  - travis_retry bash -x .travis/install.sh
  
script:
  - pytest

cache: pip

notifications:
  slack:
    secure: $SLACK_SECURE_TOKEN
